
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LEFTBRACKET = 9;
  public static final int EQUALS = 17;
  public static final int PERIOD = 2;
  public static final int RCURLYBRACKET = 6;
  public static final int RIGHTBRACKET = 10;
  public static final int LPAREN = 7;
  public static final int INT = 24;
  public static final int PRINTLN = 31;
  public static final int MINUS = 15;
  public static final int STATIC = 30;
  public static final int RPAREN = 8;
  public static final int SEMICOLON = 4;
  public static final int AND = 11;
  public static final int LESSTHAN = 12;
  public static final int COMMA = 3;
  public static final int CLASS = 19;
  public static final int PLUS = 16;
  public static final int MAIN = 26;
  public static final int IF = 23;
  public static final int EXCLAMATION = 13;
  public static final int THIS = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RETURN = 29;
  public static final int TRUE = 33;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int NUMBER = 37;
  public static final int VOID = 34;
  public static final int TIMES = 14;
  public static final int ELSE = 20;
  public static final int WHILE = 35;
  public static final int PUBLIC = 28;
  public static final int EXTENDS = 21;
  public static final int STRING = 38;
  public static final int FALSE = 22;
  public static final int LCURLYBRACKET = 5;
  public static final int LENGTH = 25;
  public static final int IDENTIFIER = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PERIOD",
  "COMMA",
  "SEMICOLON",
  "LCURLYBRACKET",
  "RCURLYBRACKET",
  "LPAREN",
  "RPAREN",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "AND",
  "LESSTHAN",
  "EXCLAMATION",
  "TIMES",
  "MINUS",
  "PLUS",
  "EQUALS",
  "BOOLEAN",
  "CLASS",
  "ELSE",
  "EXTENDS",
  "FALSE",
  "IF",
  "INT",
  "LENGTH",
  "MAIN",
  "NEW",
  "PUBLIC",
  "RETURN",
  "STATIC",
  "PRINTLN",
  "THIS",
  "TRUE",
  "VOID",
  "WHILE",
  "IDENTIFIER",
  "NUMBER",
  "STRING"
  };
}

